 self.board[0][0] = Rook(0, 0,"w")
        self.board[0][1] = Knight(0 ,1, "w")
        self.board[0][2] = Bishop(0 ,2, "w")
        self.board[0][3] = Queen(0 ,3, "w")
        self.board[0][4] = King(0 ,4, "w")
        self.board[0][5] = Bishop(0 ,5, "w")
        self.board[0][6] = Knight(0 ,6, "w")
        self.board[0][7] = Rook(0 ,7, "w")
        
        self.board[1][0] = Pawn(0, 0,"w")
        self.board[1][1] = Pawn(0 ,1, "w")
        self.board[1][2] = Pawn(0 ,2, "w")
        self.board[1][3] = Pawn(0 ,3, "w")
        self.board[1][4] = Pawn(0 ,4, "w")
        self.board[1][5] = Pawn(0 ,5, "w")
        self.board[1][6] = Pawn(0 ,6, "w")
        self.board[1][7] = Pawn(0 ,7, "w")